dist: xenial
language: python
sudo: false
env:
 - DJANGO_VERSION=2.0
 - DJANGO_VERSION=2.1
 - DJANGO_VERSION=2.2
 - DJANGO_VERSION=3.0
 - DJANGO_VERSION=3.1
 - DJANGO_VERSION=master
python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy3.5"
install:
 - if [[ $DJANGO_VERSION != master ]]; then pip install --pre -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"; fi
 - if [[ $DJANGO_VERSION == master ]]; then pip install https://github.com/django/django/archive/master.tar.gz; fi
 - pip install django-redis flake8 python3-memcached
script:
 - ./run.sh test
 - ./run.sh flake8
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=2.1
    - python: "3.4"
      env: DJANGO_VERSION=2.2
    - python: "3.4"
      env: DJANGO_VERSION=3.0
    - python: "3.4"
      env: DJANGO_VERSION=3.1
    - python: "3.4"
      env: DJANGO_VERSION=master
    - python: "3.5"
      env: DJANGO_VERSION=3.0
    - python: "3.5"
      env: DJANGO_VERSION=3.1
    - python: "3.5"
      env: DJANGO_VERSION=master
    - python: "3.8"
      env: DJANGO_VERSION=2.0
    - python: "3.8"
      env: DJANGO_VERSION=2.1
    - python: "pypy3.5"
      env: DJANGO_VERSION=3.0
    - python: "pypy3.5"
      env: DJANGO_VERSION=master
  allow_failures:
    - python: "3.6"
      env: DJANGO_VERSION=master
    - python: "3.7"
      env: DJANGO_VERSION=master
    - python: "3.8"
      env: DJANGO_VERSION=master
